import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { z } from 'zod';

const root=process.cwd(), target=join(root,'src','data'), stage=join(root,'.data-stage');
// The official catalog publishes Keren Hishtalmut rows inside Gemel Net; the
// remaining products have independent current resources (verified 2026-09-15).
const categories={gemel:'a30dcbea-a1d2-482c-ae29-8f781f5025fb',hishtalmut:'a30dcbea-a1d2-482c-ae29-8f781f5025fb',policy:'c6c62cc7-fe02-4b18-8f3e-813abfbb4647',pension:'6d47d6b5-cb08-488b-b333-f1e717b1e1bd'} as const;
type Category=keyof typeof categories; type Row=Record<string,unknown>;
const Fund=z.object({id:z.string().min(1),category:z.enum(['gemel','hishtalmut','policy','pension']),name:z.string().min(1),company:z.string().min(1),track:z.string().min(1),managementFeeDeposit:z.number().nullable(),managementFeeSavings:z.number().nullable(),returnYTD:z.number().nullable(),return1Y:z.number().nullable(),return3Y:z.number().nullable(),return5Y:z.number().nullable(),totalAssets:z.number().nullable(),history:z.array(z.object({month:z.string(),return:z.number()}))});
const Out=z.object({lastUpdated:z.string(),sourceMonth:z.string(),source:z.string(),funds:z.array(Fund).min(1)});
const agent={'User-Agent':'Mozilla/5.0 (compatible; gemel-net-data-refresh/1.0)'};
async function api(path:string){const r=await fetch(`https://data.gov.il/api/3/action/${path}`,{headers:agent});if(!r.ok)throw Error(`data.gov.il ${r.status}: ${path}`);const j=await r.json();if(!j.success)throw Error(`CKAN failure: ${path}`);return j.result}
const str=(r:Row,...keys:string[])=>{for(const k of keys)if(r[k]!=null&&String(r[k]).trim())return String(r[k]).trim();return ''};
const num=(v:unknown):number|null=>{if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/[%,₪,]/g,'').trim());return Number.isFinite(n)?n:null};
const pick=(r:Row,...keys:string[])=>{for(const k of keys)if(k in r)return num(r[k]);return null};
function month(r:Row){const v=str(r,'REPORT_PERIOD','REPORT_DATE','תקופת_דיווח','חודש דיווח');const m=v.match(/(\d{4})[-/]?(\d{2})/);return m?`${m[1]}-${m[2]}`:''}
function normalise(category:Category,rows:Row[]){
 const latest=new Map<string,Row>(), history=new Map<string,{month:string;return:number}[]>();
 for(const r of rows){const id=str(r,'FUND_ID','FUND_CODE','KUPA_ID','מספר_קופה','קוד_מסלול');if(!id)continue;const m=month(r), y=pick(r,'MONTHLY_YIELD','MONTHLY_RETURN','תשואה_חודשית');if(m&&y!==null){const h=history.get(id)||[];h.push({month:m,return:y});history.set(id,h)}if(!latest.has(id)||m>month(latest.get(id)!))latest.set(id,r)}
 return [...latest].map(([id,r])=>{const h=(history.get(id)||[]).sort((a,b)=>a.month.localeCompare(b.month));const one=h.slice(-12).reduce((a,x)=>a*(1+x.return/100),1);return {id,category,name:str(r,'FUND_NAME','NAME','שם_קופה','שם מסלול'),company:str(r,'MANAGING_CORPORATION','MANAGING_COMPANY','חברה_מנהלת','שם חברה מנהלת')||'לא פורסם',track:str(r,'FUND_CLASSIFICATION','TRACK_NAME','SPECIALIZATION','מסלול השקעה','התמחות')||'כללי',managementFeeDeposit:pick(r,'AVG_DEPOSIT_FEE','DEPOSIT_MANAGEMENT_FEE','דמי_ניהול_מהפקדה'),managementFeeSavings:pick(r,'AVG_ANNUAL_MANAGEMENT_FEE','MANAGEMENT_FEE','דמי_ניהול_מצבירה'),returnYTD:pick(r,'YEAR_TO_DATE_YIELD','YTD_YIELD','תשואה_מתחילת_שנה'),return1Y:h.length>=12?(one-1)*100:pick(r,'YIELD_TRAILING_1_YR','YIELD_TRAILING_12_MONTHS','תשואה_שנה'),return3Y:pick(r,'YIELD_TRAILING_3_YRS','YIELD_3_YEARS','תשואה_3_שנים'),return5Y:pick(r,'YIELD_TRAILING_5_YRS','YIELD_5_YEARS','תשואה_5_שנים'),totalAssets:pick(r,'TOTAL_ASSETS','ASSETS','סך_נכסים'),history:h.slice(-60)}}).filter(x=>x.name).filter(x=>category==='hishtalmut'?/השתלמות/.test(x.track):category==='gemel'?!/השתלמות/.test(x.track):true);
}
async function records(resource:string){let offset=0,total=Infinity,out:Row[]=[];while(offset<total){const r=await api(`datastore_search?resource_id=${resource}&limit=5000&offset=${offset}`);out.push(...r.records);total=r.total;offset+=r.records.length;if(!r.records.length)break}if(!out.length)throw Error(`No rows for resource ${resource}`);return out}
async function previousCount(category:Category){try{return Out.parse(JSON.parse(await readFile(join(target,`${category}.json`),'utf8'))).funds.length}catch{return 0}}
async function main(){await rm(stage,{recursive:true,force:true});await mkdir(stage,{recursive:true});const outputs:Record<string,unknown>={};for(const [category,resource] of Object.entries(categories) as [Category,string][]){const rows=await records(resource),funds=normalise(category,rows);const old=await previousCount(category);if(old&&funds.length<old*.8)throw Error(`${category}: fund count fell from ${old} to ${funds.length}; refusing partial or changed schema`);const sourceMonth=month(rows.reduce((a,b)=>month(a)>month(b)?a:b));outputs[category]=Out.parse({lastUpdated:new Date().toISOString().slice(0,10),sourceMonth,source:`data.gov.il (${resource})`,funds});await writeFile(join(stage,`${category}.json`),JSON.stringify(outputs[category]),'utf8');console.log(`${category}: ${funds.length} funds`)}await mkdir(target,{recursive:true});for(const category of Object.keys(categories))await rename(join(stage,`${category}.json`),join(target,`${category}.json`));await rm(stage,{recursive:true,force:true})}
main().catch(async e=>{await rm(stage,{recursive:true,force:true});console.error(e);process.exitCode=1});
